package com.contest.platform.model;
public enum SubmissionStatus { QUEUED, COMPILING, RUNNING, ACCEPTED, WRONG_ANSWER, COMPILATION_ERROR, RUNTIME_ERROR, TIME_LIMIT_EXCEEDED, MEMORY_LIMIT_EXCEEDED, SYSTEM_ERROR }
